# Generated by Django 4.2.15 on 2026-05-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="erified_by",
            new_name="verified_by",
        ),
    ]
