# Generated by Django 4.2.15 on 2026-05-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_erified_by_bankaccount_verified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="fully_activated",
            field=models.BooleanField(default=False, verbose_name="Fully Activated"),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="verification_notes",
            field=models.TextField(blank=True, verbose_name="Verification Notes"),
        ),
    ]
