# Generated by Django 4.2.15 on 2026-06-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_bankaccount_fully_activated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Annual interest rate for savings accounts",
                max_digits=5,
                verbose_name="Interest Rate (%)",
            ),
        ),
    ]
